package main

import (
	"fmt"
	"os"

	"github.com/alexsasharegan/dotenv"
	"github.com/techforward/ECscript_server/routes"

	_ "github.com/techforward/ECscript_server/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/labstack/echo"
	"github.com/labstack/echo/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title ECSite API
// @version 1.0
// @description API for the ECSite
// @license.name Techforward Inc.
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:1323
// @BasePath /
func main() {

	_ = dotenv.Load()

	fmt.Println("mode: ", os.Getenv("MODE"))

	AllowOrigins := []string{"http://localhost", "*"}
	AllowHeaders := []string{echo.HeaderOrigin, echo.HeaderContentType, echo.HeaderAccept}

	e := echo.New()
	// swagger
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: AllowOrigins,
		AllowHeaders: AllowHeaders,
	}))
	// e.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
	// 	Format: "time:${time_rfc3339_nano},method=${method}, uri=${uri}, status=${status}, error=${error}\n",
	// }))

	routes.Router(e)

	port := os.Getenv("PORT")
	if port == "" {
		port = "1323"
	}
	e.Logger.Fatal(e.Start(":" + port))
}
