development:
  db:
    user: api
    password: api
    name: ecsite
    ip: 35.221.187.41
    port: 3306
local_development:
  db:
    user: test
    password: test
    name: development
    ip: 127.0.0.1
    port: 3306
test:
  db:
    user: test
    password: test
    name: test
    ip: 127.0.0.1
    port: 3306
    